[global]
strict init      = true
buffer min       = 1024
buffer max       = 2MB
rotate lock file = /tmp/zlog.lock
default format   = "%d(%Y-%m-%d) %-6V (%c:%F:%U:%L) %m"
fsync period     = 100

[formats]
null	=		"%n"
print	=		"print - [%-10.3d(%Y-%m-%d)]%m%n"

simple	=		"%m%n"

debug	=		"[%d(%Y-%m-%d %H:%M:%S).%ms] [%-6V] (%c:%F:%U:%L) %m"

info	=		"[%d(%Y-%m-%d %H:%M:%S).%ms] [%-6V] %m"

[rules]
test.info		>stdout;info
lidar_emap.*	>stdout;debug
lidar_emap.*	"/var/log/lidar_emap.log",1MB * 3 ~ "/var/log/lidar_emap_%d(%Y%m%d).#r.log";debug
