N_SCAN: 16                                  # number of lidar channel (i.e., Velodyne/Ouster: 16, 32, 64, 128, Livox Horizon: 6)
  # 分辨率
Horizon_SCAN: 1800         
  # 降低点云密度，例如，如果 downsampleRate=2，则只处理偶数线束（或奇数，取决于实现）的点
downsampleRate: 1 
lidarFrame: "lidar_link"
#  距离过小认为是自身噪声，过大认为精度很差
lidarMinRange: 1.0                          # default: 1.0, minimum lidar range to be used
lidarMaxRange: 1000.0                       # default: 1000.0, maximum lidar range to be used
pointCloudTopic: "/rslidar_points"   
sensor: rs                 # Point cloud data
imuTopic: "imu/data"                         # IMU data
outputTopic: "cloud_deskewed"
extrinsicRot: [1, 0, 0,
                0, 1, 0,
                0, 0, 1]
extrinsicRPY: [1,  0, 0,
                0, 1, 0,
                0, 0, 1]
